### ISSUE TITLE
预训练模型无法下载

### ISSUE THREAD

**Issue by Lasciarti** [linwhitehat/ET-BERT#1]
您好，下载预训练模型时显示需要申请，请问可以开放一下权限吗？

**Comment by linwhitehat** [comment]
> 您好，下载预训练模型时显示需要申请，请问可以开放一下权限吗？

抱歉，共享在谷歌网盘后不知道有权限问题。
目前已经修改谷歌网盘权限，可查看和下载。

**Comment by Lasciarti** [comment]
您好，邮件已收到，谢谢！
