### ISSUE TITLE
pre-training/pretrain.py 里面使用的dataset.pt数据集是怎么产生呢

### ISSUE THREAD

**Issue by HelloWorldBeginner** [linwhitehat/ET-BERT#10]
作者你好，我大概看了项目代码，没有找到dataset.pt生成的方式，这边预训练模型需要使用这个数据集，也可能是我遗漏了些代码，希望作者解惑。

**Comment by linwhitehat** [comment]
> 作者你好，我大概看了项目代码，没有找到dataset.pt生成的方式，这边预训练模型需要使用这个数据集，也可能是我遗漏了些代码，希望作者解惑。

你好，感谢对我们工作的关注。
你提到的这个`dataset.pt`是通过调用主目录下的`preprocess.py`对处理好的预训练流量生成的预训练数据集，可以查看说明中关于pre-process的使用。

**Comment by Kaleidoscope-arch** [comment]
> > 作者你好，我大概看了项目代码，没有找到dataset.pt生成的方式，这边预训练模型需要使用这个数据集，也可能是我遗漏了些代码，希望作者解惑。
> 
> 你好，感谢对我们工作的关注。 你提到的这个`dataset.pt`是通过调用主目录下的`preprocess.py`对处理好的预训练流量生成的预训练数据集，可以查看说明中关于pre-process的使用。

请问这个dataset.pt和encryptd_vocab.txt之间的关系是什么呢？
