### ISSUE TITLE
Some questions about equipment requirements

### ISSUE THREAD

**Issue by xiaozongziya** [linwhitehat/ET-BERT#11]
Hi, I'm trying to reproduce ET-BERT recently. I followed the steps in the README you provided. When I run preprocess.py to pre-process the encrypted traffic burst corpusre, I found that the program will interrupt and exit in the middle of the execution. I don’t know if my equipment conditions are not up to the requirements. What is the performance of the equipment you used in the experiment, such as cpu, gpu, memory size, etc. Looking forward to your reply. Thank you!

**Comment by linwhitehat** [comment]
> Hi, I'm trying to reproduce ET-BERT recently. I followed the steps in the README you provided. When I run preprocess.py to pre-process the encrypted traffic burst corpusre, I found that the program will interrupt and exit in the middle of the execution. I don’t know if my equipment conditions are not up to the requirements. What is the performance of the equipment you used in the experiment, such as cpu, gpu, memory size, etc. Looking forward to your reply. Thank you!

Thanks for your following. The equipment for our experiment is as followed:
Available CPU are Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz x 96
Available memory is 502 GB
Available GPU are Tesla V100S (32GB) x 4
