### ISSUE TITLE
Question about Pre-Trained Model provided in Github.

### ISSUE THREAD

**Issue by network-traffic** [linwhitehat/ET-BERT#12]
First of all, thanks for your great research work!

I just want to know whether the pre-trained model is ET-BERT(packet)? or it also includes ET-BERT(flow)?

I want to do a flow-level classification task (which input of the task is a flow), and it seems that your pre-trained model, provided through github, is for packet-level. (Please tell me if I was wrong)

Is it fine to use the pre-trained model and fine-tuning it with flow-level dataset, pre-processed by "/data_process/main.py" with "dataset_level = flow"?

Or is there any pre-trained model "**ET-BERT(flow)**"?

Thanks a lot.

**Comment by linwhitehat** [comment]
> First of all, thanks for your great research work!
> 
> I just want to know whether the pre-trained model is ET-BERT(packet)? or it also includes ET-BERT(flow)?
> 
> I want to do a flow-level classification task (which input of the task is a flow), and it seems that your pre-trained model, provided through github, is for packet-level. (Please tell me if I was wrong)
> 
> Is it fine to use the pre-trained model and fine-tuning it with flow-level dataset, pre-processed by "/data_process/main.py" with "dataset_level = flow"?
> 
> Or is there any pre-trained model "**ET-BERT(flow)**"?
> 
> Thanks a lot.

Thank you for your interest in our work.
Our publicly available pre-trained model is available for both packet level and flow level.

**Comment by network-traffic** [comment]
I understood. Thanks for your reply!
