### ISSUE TITLE
Some questions about the datasets.

### ISSUE THREAD

**Issue by boyofguan** [linwhitehat/ET-BERT#13]
Hello, we want to use the preprocessed USTC-TFC, ISCX-VPN-Service and ISCX-VPN-App dataset directly, but we don't find the download link of USTC-TFC dataset in your project. In addition, would you provide which category each label index value of these three datasets represents? Because we have the need for further specific division. 
Thank you.

**Comment by linwhitehat** [comment]
> Hello, we want to use the preprocessed USTC-TFC, ISCX-VPN-Service and ISCX-VPN-App dataset directly, but we don't find the download link of USTC-TFC dataset in your project. In addition, would you provide which category each label index value of these three datasets represents? Because we have the need for further specific division. Thank you.

We are glad to have your interest in our work. And we have added the corresponding datasets as well as the label descriptions, which can be viewed [here](https://github.com/linwhitehat/ET-BERT/blob/main/datasets/README.md).
