### ISSUE TITLE
[dataset] What exactly are the 120 categories in the cstnet-tls1.3 dataset?

### ISSUE THREAD

**Issue by lealaxy** [linwhitehat/ET-BERT#15]
Hello, what is the content of the tags for each of the 120 categories in the dataset？

**Comment by linwhitehat** [comment]
> Hello, what is the content of the tags for each of the 120 categories in the dataset？

The detail of the categories is as below:
|-- 163.com
|-- 51.la
|-- 51cto.com
|-- acm.org
|-- adobe.com
|-- alibaba.com
|-- alicdn.com
|-- alipay.com
|-- amap.com
|-- amazonaws.com
|-- ampproject.org
|-- apple.com
|-- arxiv.org
|-- asus.com
|-- atlassian.net
|-- azureedge.net
|-- baidu.com
|-- bilibili.com
|-- biligame.com
|-- booking.com
|-- chia.net
|-- chinatax.gov.cn
|-- cisco.com
|-- cloudflare.com
|-- cloudfront.net
|-- cnblogs.com
|-- codepen.io
|-- crazyegg.com
|-- criteo.com
|-- ctrip.com
|-- dailymotion.com
|-- deepl.com
|-- digitaloceanspaces.com
|-- duckduckgo.com
|-- eastday.com
|-- eastmoney.com
|-- elsevier.com
|-- facebook.com
|-- feishu.cn
|-- ggpht.com
|-- github.com
|-- gitlab.com
|-- gmail.com
|-- goat.com
|-- google.com
|-- grammarly.com
|-- gravatar.com
|-- guancha.cn
|-- huanqiu.com
|-- huawei.com
|-- hubspot.com
|-- huya.com
|-- ibm.com
|-- icloud.com
|-- ieee.org
|-- instagram.com
|-- iqiyi.com
|-- jb51.net
|-- jd.com
|-- kugou.com
|-- leetcode-cn.com
|-- media.net
|-- mi.com
|-- microsoft.com
|-- mozilla.org
|-- msn.com
|-- naver.com
|-- netflix.com
|-- nike.com
|-- notion.so
|-- nvidia.com
|-- office.net
|-- onlinedown.net
|-- opera.com
|-- oracle.com
|-- outbrain.com
|-- overleaf.com
|-- paypal.com
|-- pinduoduo.com
|-- python.org
|-- qcloud.com
|-- qq.com
|-- researchgate.net
|-- runoob.com
|-- sciencedirect.com
|-- semanticscholar.org
|-- sina.com.cn
|-- smzdm.com
|-- snapchat.com
|-- sohu.com
|-- spring.io
|-- springer.com
|-- squarespace.com
|-- statcounter.com
|-- steampowered.com
|-- t.co
|-- taboola.com
|-- teads.tv
|-- thepaper.cn
|-- tiktok.com
|-- toutiao.com
|-- twimg.com
|-- twitter.com
|-- unity3d.com
|-- v2ex.com
|-- vivo.com.cn
|-- vk.com
|-- vmware.com
|-- walmart.com
|-- weibo.com
|-- wikimedia.org
|-- wikipedia.org
|-- wp.com
|-- xiaomi.com
|-- ximalaya.com
|-- yahoo.com
|-- yandex.ru
|-- youtube.com
|-- yy.com
`-- zhihu.com

**Comment by lealaxy** [comment]
thank you!
