### ISSUE TITLE
Some questions about data generation

### ISSUE THREAD

**Issue by 11asdad** [linwhitehat/ET-BERT#18]
你好，我运行了预训练和fine-tuning两种生成数据的脚本，得到的npy文件仅有datagram和标签两种，但我看到cstnet示例数据中还有len、direction、message_type和time类型的npy文件，我在代码中搜索这些文件名也没有找到相关的写入文件的代码，请问这些npy文件是必需的吗？该如何生成？

另外我有一批自己捕获的非pcpa格式的数据，包含了报文的16进制和五元组，可以直接自己构造数据文件吗？应当依照哪种格式？如果参照上述情况仅构造datagram和标签两种npy文件，该如何让算法知道哪些数据属于同源BURST？

Hello, I have run pre-training and fine-tuning scripts to generate data, and the only npy files I can get are `datagram` and ` tag`. However, I can see that there are also npy files of `len`, `direction`, `Message_type` and `time` types in cstnet sample data. I searched these file names in the code and did not find the relevant code for writing files. Are these npy files required? How do I generate it?

In addition, I have a batch of data in non-PCPA format captured by myself, including hexadecimal and quintuple of packets. Can I directly construct data files by myself? Which format should be followed? If I construct only datagram and tag npy files based on the above situation, how do I let the algorithm know which data belongs to the same BURST?

**Comment by linwhitehat** [comment]
> 你好，我运行了预训练和fine-tuning两种生成数据的脚本，得到的npy文件仅有datagram和标签两种，但我看到cstnet示例数据中还有len、direction、message_type和time类型的npy文件，我在代码中搜索这些文件名也没有找到相关的写入文件的代码，请问这些npy文件是必需的吗？该如何生成？
> 
> 另外我有一批自己捕获的非pcpa格式的数据，包含了报文的16进制和五元组，可以直接自己构造数据文件吗？应当依照哪种格式？如果参照上述情况仅构造datagram和标签两种npy文件，该如何让算法知道哪些数据属于同源BURST？
> 
> Hello, I have run pre-training and fine-tuning scripts to generate data, and the only npy files I can get are `datagram` and ` tag`. However, I can see that there are also npy files of `len`, `direction`, `Message_type` and `time` types in cstnet sample data. I searched these file names in the code and did not find the relevant code for writing files. Are these npy files required? How do I generate it?
> 
> In addition, I have a batch of data in non-PCPA format captured by myself, including hexadecimal and quintuple of packets. Can I directly construct data files by myself? Which format should be followed? If I construct only datagram and tag npy files based on the above situation, how do I let the algorithm know which data belongs to the same BURST?

你好，很感谢你对本工作的关注。
除了datagram以外的数据都不是本工作所必须的，公开的cstnet数据集包含其他类型特征数据是方便提供给其他研究进行对比使用。
根据你的数据是可以自己构造数据文件，但是需要自己修改代码逻辑（包级别和流级别需要自行区分，然后在dataset_generation.py中的get_feature_packet和get_feature_flow中将packet_string替换为你的报文数据接口）。同源BURST的判别可根据五元组的方向进行处理。

**Comment by 11asdad** [comment]
> 同源BURST的判别可根据五元组的方向进行处理。
datagram和corpora中好像都不包含五元组的信息，模型是从哪个文件得知的？

**Comment by linwhitehat** [comment]
> > 同源BURST的判别可根据五元组的方向进行处理。
> 
> datagram和corpora中好像都不包含五元组的信息，模型是从哪个文件得知的？

这部分是根据原始pcap中的五元组进行抽取后判断的，而不是基于后续生成的datagram或corpora。

**Comment by 11asdad** [comment]
成功了√谢谢

**Comment by ctr555** [comment]
你好我想问问怎么自己弄一个新的数据集呀！
