### ISSUE TITLE
which tensor is used in A.1 of your paper?

### ISSUE THREAD

**Issue by 11asdad** [linwhitehat/ET-BERT#19]
你好，请问在论文A.1部分用于可视化的向量是embedding的输出还是classification内部的向量？
这部分代码可以分享一下吗？我想用类似A.1的方式观察fine-tuning后的模型效果，但在推理代码`run_classifier_infer.py`中没能找到输出embedding结果的方式

**Comment by linwhitehat** [comment]
> 你好，请问在论文A.1部分用于可视化的向量是embedding的输出还是classification内部的向量？ 这部分代码可以分享一下吗？我想用类似A.1的方式观察fine-tuning后的模型效果，但在推理代码`run_classifier_infer.py`中没能找到输出embedding结果的方式

你好，可视化部分的表示向量是模型输出的embedding，可以在模型输出部分的evaluate函数或者[推理部分](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的model输出进行修改，可视化代码使用的是t-sne表示。

**Comment by 11asdad** [comment]
支持直接使用uer-py的extract_features提取吗？

**Comment by 11asdad** [comment]
> 

是倒数第二层吗？

**Comment by linwhitehat** [comment]
> 支持直接使用uer-py的extract_features提取吗？

这个没试过。

**Comment by linwhitehat** [comment]
> > > 你好，请问在论文A.1部分用于可视化的向量是embedding的输出还是classification内部的向量？ 这部分代码可以分享一下吗？我想用类似A.1的方式观察fine-tuning后的模型效果，但在推理代码`run_classifier_infer.py`中没能找到输出embedding结果的方式
> > 
> > 
> > 你好，可视化部分的表示向量是模型输出的embedding，可以在模型输出部分的evaluate函数或者[推理部分](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的model输出进行修改，可视化代码使用的是t-sne表示。
> 
> 是倒数第二层吗？

是的，在输入分类器之前的表征结果。在[代码](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的131行可以调取model(src_batch, None, seg_batch)

**Comment by 11asdad** [comment]
> > > > 你好，请问在论文A.1部分用于可视化的向量是embedding的输出还是classification内部的向量？ 这部分代码可以分享一下吗？我想用类似A.1的方式观察fine-tuning后的模型效果，但在推理代码`run_classifier_infer.py`中没能找到输出embedding结果的方式
> > > 
> > > 
> > > 你好，可视化部分的表示向量是模型输出的embedding，可以在模型输出部分的evaluate函数或者[推理部分](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的model输出进行修改，可视化代码使用的是t-sne表示。
> > 
> > 
> > 是倒数第二层吗？
> 
> 是的，在输入分类器之前的表征结果。在[代码](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的131行可以调取model(src_batch, None, seg_batch)

谢谢！我看`model(src_batch, None, seg_batch)`的输出已经被线形层变形成了维度数=类别数，和使用倒数第二层的768维的tensor相比，是否会损失太多信息？想看模型的表征能力的话使用倒数第二层的768维的tensor会更好吗？论文中使用的是哪一种？

**Comment by linwhitehat** [comment]
> > > > > 你好，请问在论文A.1部分用于可视化的向量是embedding的输出还是classification内部的向量？ 这部分代码可以分享一下吗？我想用类似A.1的方式观察fine-tuning后的模型效果，但在推理代码`run_classifier_infer.py`中没能找到输出embedding结果的方式
> > > > 
> > > > 
> > > > 你好，可视化部分的表示向量是模型输出的embedding，可以在模型输出部分的evaluate函数或者[推理部分](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的model输出进行修改，可视化代码使用的是t-sne表示。
> > > 
> > > 
> > > 是倒数第二层吗？
> > 
> > 
> > 是的，在输入分类器之前的表征结果。在[代码](https://github.com/linwhitehat/ET-BERT/blob/main/inference/run_classifier_infer.py)的131行可以调取model(src_batch, None, seg_batch)
> 
> 谢谢！我看`model(src_batch, None, seg_batch)`的输出已经被线形层变形成了维度数=类别数，和使用倒数第二层的768维的tensor相比，是否会损失太多信息？想看模型的表征能力的话使用倒数第二层的768维的tensor会更好吗？论文中使用的是哪一种？

对的，这部分维度已经改变，在论文中使用的是这部分表征结果。因为这里已经做了一次降维，信息是存在一定损失的，但是从最终可视化区分结果上没有太大的影响，欢迎做信息损失评估，后续有时间我也会加上这部分分析以选取更合适的表征结果。
