### ISSUE TITLE
what's the meaning of word_name_iscx in line 126 of main.py 

### ISSUE THREAD

**Issue by yekebuda** [linwhitehat/ET-BERT#2]
what's the meaning of word_name_iscx in line 126 of main.py (data_process fold)

**Comment by linwhitehat** [comment]
> what's the meaning of word_name_iscx in line 126 of main.py (data_process fold)

This is the variable used when testing the iscx dataset and its function is the same as  *word_name*.
Thanks for the question, the code has now been corrected.

**Comment by yekebuda** [comment]
Thanks for your reply. The process of reading code is very laborious. Can the author recheck the code provided, simplify the code and remove the not running codes? It would be great to provide explicit variable definitions.

**Comment by linwhitehat** [comment]
> Thanks for your reply. The process of reading code is very laborious. Can the author recheck the code provided, simplify the code and remove the not running codes? It would be great to provide explicit variable definitions.

Thank you for your feedback, we will improve the code quality in our follow-up work.
