### ISSUE TITLE
你好，我在运行您的代码的过程中出现了些报错，想请教您是否知道如何解决

### ISSUE THREAD

**Issue by Szthing** [linwhitehat/ET-BERT#20]
tarfile.py文件报错，我花了很久也没找到解决方法  555┭┮﹏┭┮
![QQ图片20220530172119](https://user-images.githubusercontent.com/37261209/170961210-48355b71-8d9f-4047-9916-9fa19740dcc3.png)

**Comment by linwhitehat** [comment]
> tarfile.py文件报错，我花了很久也没找到解决方法 555┭┮﹏┭┮ ![QQ图片20220530172119](https://user-images.githubusercontent.com/37261209/170961210-48355b71-8d9f-4047-9916-9fa19740dcc3.png)

你好，感谢你对我们工作的关注。查看你报错的原因应该是和torch版本有关系，不是代码层面的问题，你可以升级版本或者查看这个[issue](https://github.com/pytorch/pytorch/issues/43766)，希望能帮助到你。

**Comment by Szthing** [comment]
万分感谢 我去试试

**Comment by linwhitehat** [comment]
> 万分感谢 我去试试

不客气，如果觉得我们的工作不错，欢迎star和fork

**Comment by Szthing** [comment]
> 

好勒
