### ISSUE TITLE
packages problem

### ISSUE THREAD

**Issue by ctr555** [linwhitehat/ET-BERT#23]
Why my conda says needs python version to be 2.6 to install argparse, I have searched on the Google but didn't find the solution.
<img width="822" alt="截屏2022-07-02 22 41 08" src="https://user-images.githubusercontent.com/77194157/177005287-3129ced7-471e-4f53-93ff-a6755a6623af.png">

**Comment by linwhitehat** [comment]
> Why my conda says needs python version to be 2.6 to install argparse, I have searched on the Google but didn't find the solution. <img alt="截屏2022-07-02 22 41 08" width="822" src="https://user-images.githubusercontent.com/77194157/177005287-3129ced7-471e-4f53-93ff-a6755a6623af.png">

Hi, thank you for your interest in our work.  This library does not need to be installed independently in python version 2.7 and above, and belongs to is a standard library.
