### ISSUE TITLE
GPU configuration

### ISSUE THREAD

**Issue by sljx** [linwhitehat/ET-BERT#24]
Our lab is also interested in applying BERT to network traffic anomaly detection, so I'm curious about the exact configuration of your server's GPU , for example, how many graphics cards，and I'd appreciate it if you could answer.

**Comment by linwhitehat** [comment]
> Our lab is also interested in applying BERT to network traffic anomaly detection, so I'm curious about the exact configuration of your server's GPU , for example, how many graphics cards，and I'd appreciate it if you could answer.

Thanks for your interest in our study. The detail of the configuration can be seen here #11 .
