### ISSUE TITLE
No module named 'uer'

### ISSUE THREAD

**Issue by ctr555** [linwhitehat/ET-BERT#25]
When I try to run pretrain.py to pre-train,there is a mistake happed.
I really need you help
<img width="1123" alt="截屏2022-07-16 18 31 17" src="https://user-images.githubusercontent.com/77194157/179351284-1bf1944f-e7f8-455e-8b0b-7cf9eccb015b.png">

**Comment by linwhitehat** [comment]
> When I try to run pretrain.py to pre-train,there is a mistake happed. I really need you help <img alt="截屏2022-07-16 18 31 17" width="1123" src="https://user-images.githubusercontent.com/77194157/179351284-1bf1944f-e7f8-455e-8b0b-7cf9eccb015b.png">

The `uer` directory is in the root directory and you can refer here #6  to set it.

**Comment by ctr555** [comment]
Thank you ,I successfully solve this problem！！
And then I try to run the code:
<img width="838" alt="截屏2022-07-17 09 53 54" src="https://user-images.githubusercontent.com/77194157/179380698-0c4c23c9-6060-4fad-a868-bdde827c8314.png">
And there is another mistake:
<img width="1153" alt="截屏2022-07-17 09 54 26" src="https://user-images.githubusercontent.com/77194157/179380707-17f3e6fc-dea8-4eff-9f06-feee2e952224.png">

**Comment by linwhitehat** [comment]
> Thank you ,I successfully solve this problem！！ And then I try to run the code: <img alt="截屏2022-07-17 09 53 54" width="838" src="https://user-images.githubusercontent.com/77194157/179380698-0c4c23c9-6060-4fad-a868-bdde827c8314.png"> And there is another mistake: <img alt="截屏2022-07-17 09 54 26" width="1153" src="https://user-images.githubusercontent.com/77194157/179380707-17f3e6fc-dea8-4eff-9f06-feee2e952224.png">

Please check if your data paths are accurate, you need to calibrate the file paths that exist in the parameters according to your own experimental environment.

**Comment by Codebilibili** [comment]
> 谢谢，我成功解决了这个问题！！ 然后我尝试运行代码： 还有一个错误： <img alt="截屏2022-07-17 09 53 54" width="838" src="https://user-images.githubusercontent.com/77194157/179380698-0c4c23c9-6060-4fad-a868-bdde827c8314.png"> <img alt="截屏2022-07-17 09 54 26" width="1153" src="https://user-images.githubusercontent.com/77194157/179380707-17f3e6fc-dea8-4eff-9f06-feee2e952224.png">

How did you solve ModuleNotFoundError: No module named 'uer'
