### ISSUE TITLE
where is `models/encryptd_vocab.txt` come from?

### ISSUE THREAD

**Issue by 11asdad** [linwhitehat/ET-BERT#26]
你好，请问示例命令中使用的的models/encryptd_vocab.txt是在corpora中的谷歌云链接中下载的encrypted_traffic_burst.txt上得到的吗？好像与我生成的不一样

**Comment by linwhitehat** [comment]
> 你好，请问示例命令中使用的的models/encryptd_vocab.txt是在corpora中的谷歌云链接中下载的encrypted_traffic_burst.txt上得到的吗？好像与我生成的不一样

你好，感谢你对我们的研究工作的关注。

我们使用的字典encrypted_vocab不是通过预训练corpora生成的，而是通过私有的一个大规模流量数据库进行构造的，字典的作用只是给一个参照，并一定包含所有训练阶段的数据。

**Comment by 11asdad** [comment]
明白了，谢谢!
另外我看到models文件夹下除了`encryptd_vocab.txt`还有一个`encryptd_vocab_base.txt`，请问这个是如何生成的？它里面的词的个数也与`encryptd_vocab.txt`不同，如果更换vocab需要在pretrain代码里修改embedding层形状吗？uer是否会自动地变换形状

**Comment by linwhitehat** [comment]
> 明白了，谢谢! 另外我看到models文件夹下除了`encryptd_vocab.txt`还有一个`encryptd_vocab_base.txt`，请问这个是如何生成的？ 它里面的词的个数也与`encryptd_vocab.txt`和我通过预训练corpora生成的都不同，如果更换vocab需要在pretrain代码里修改embedding层形状吗，uer是否会自动地变换形状？ 可以分享一下你们在加密场景词表大小选择的思考吗，以及为什么选择做overlap而不是输入hex序列让tokenizer自行组合，是尝试过拼出来的词太少吗？ 由于max_input_chars_per_word仅为4，似乎生成的vocab和通过列举所有十六进制4位数+标记初始化出来的vocab差异比较小，可以分享一下这里对训练tokenization的贡献的评估吗，在私有大规模数据上训练的vocab、小规模上训练的vocab和朴素的直接列举所有十六进制4位数得到的vocab 三者之间的差距如何？谢谢！

vocab的改变不需要去修改模型，这里构造vocab的思路主要是提供更高频的token，理论上也可以使用全量的2字节token，但是在vocab规模灵活性方面便弱化了，这部分即分词、构表的阶段，vocab本身是作为模型训练中token映射到向量的作用，在定义小单元的token时可以使用全量的vocab，而我们的处理是一种更为灵活也是常见的分词构表方式。

**Comment by 11asdad** [comment]
了解了√谢谢！
