### ISSUE TITLE
你好！我想问一下ISCX-VPN（service和app）这个数据集是如何形成的！

### ISSUE THREAD

**Issue by ctr555** [linwhitehat/ET-BERT#27]
我在官网下载了ISCX的数据集
<img width="774" alt="截屏2022-08-11 18 26 41" src="https://user-images.githubusercontent.com/77194157/184114218-bff5712a-2804-4b71-b95d-113182ec10a8.png">
<img width="811" alt="截屏2022-08-11 18 26 53" src="https://user-images.githubusercontent.com/77194157/184114259-e3cd75e9-6d0e-4dde-b631-6dcca430f036.png">
跟您这边提供的分类有点不一致
<img width="366" alt="截屏2022-08-11 18 27 02" src="https://user-images.githubusercontent.com/77194157/184114283-3df9b1e3-ccf5-48fa-a81b-21c9a276d606.png">
我想问问这个数据集经过了怎样的Datagram2Token预处理才变成论文中的RUBST输入！

**Comment by linwhitehat** [comment]
> 

你好，我的数据集分类是按照ISCX-VPN的说明进行分类的，一共可分为12类，即service类别，app类别是根据作者提供的说明进行细分的类别。
![image](https://user-images.githubusercontent.com/20349381/184274359-0df9a1c5-ba06-4c19-9464-05304cb5db4b.png)
BURST处理可以参照#18

**Comment by JieJiemua** [comment]
您列出来的第十个标签Tor流量，并没有在您给出的关于流量分类的说明中看到，Tor流量我在官方下载的数据集里面也没有看到，请问tor流量也是包含在iscxVPN这个数据集中的吗？

**Comment by RicardoMLi** [comment]
> 您列出来的第十个标签Tor流量，并没有在您给出的关于流量分类的说明中看到，Tor流量我在官方下载的数据集里面也没有看到，请问tor流量也是包含在iscxVPN这个数据集中的吗？

我也遇到了这种情况，请问您怎么解决的呢？

**Comment by CMV-1** [comment]
可以分享一下按service和app划分好的pcap文件吗？

**Comment by wenhan-debug** [comment]
> > 
> 
> 你好，我的数据集分类是按照ISCX-VPN的说明进行分类的，一共可分为12类，即service类别，app类别是根据作者提供的说明进行细分的类别。 ![image](https://user-images.githubusercontent.com/20349381/184274359-0df9a1c5-ba06-4c19-9464-05304cb5db4b.png) BURST处理可以参照#18

您好，您有torrent01.pcap文件吗，可以发给我吗，我的邮箱是wenhan_li@163.com，十分感谢您

**Comment by papipapilala** [comment]
> 可以分享一下按service和app划分好的pcap文件吗？

请问您获取到了吗？若获取到是否可以分享到邮箱1554022598@qq.com。不胜感激

**Comment by Clow5211** [comment]
您好，您有Torrent01.pcap文件吗，可以发给我吗，我的邮箱是[clow0414@gmail.com]，十分感谢
