### ISSUE TITLE
Error when running the finetuning code

### ISSUE THREAD

**Issue by satyandraguthula** [linwhitehat/ET-BERT#29]
Hi authors,
I keep encountering the following error when trying to reproduce your code. Have you been through this?

../aten/src/ATen/native/cuda/Loss.cu:271: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:271: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
  0%|                                                                                                                                                                                | 0/10 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "<string>", line 182, in train_model
  File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "<string>", line 61, in forward
  File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 211, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2689, in nll_loss
    return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: CUDA error: device-side assert triggered

**Comment by linwhitehat** [comment]
> Hi authors, I keep encountering the following error when trying to reproduce your code. Have you been through this?
> 
> ../aten/src/ATen/native/cuda/Loss.cu:271: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed. ../aten/src/ATen/native/cuda/Loss.cu:271: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed. 0%| | 0/10 [00:01<?, ?it/s] Traceback (most recent call last): File "", line 4, in File "", line 182, in train_model File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "", line 61, in forward File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/modules/loss.py", line 211, in forward return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction) File "/home/satyandra/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 2689, in nll_loss return torch._C._nn.nll_loss_nd(input, target, weight, _Reduction.get_enum(reduction), ignore_index) RuntimeError: CUDA error: device-side assert triggered

This problem seems to be caused by the label of the data, while suggesting that you debug to confirm the problem, similar to this answer[https://stackoverflow.com/questions/51691563/cuda-runtime-error-59-device-side-assert-triggered](https://stackoverflow.com/questions/51691563/cuda-runtime-error-59-device-side-assert-triggered)
