### ISSUE TITLE
Hardware configuration problem

### ISSUE THREAD

**Issue by lincgcg** [linwhitehat/ET-BERT#3]

**Comment by linwhitehat** [comment]
> #### We encountered some problems in the process of reproducing the model.
> #### Can you tell us your hardware configuration, for example, how much memory？ how many GPUs？what type of GPUs？ because we found that we were running out of memory during the reproduction process.

Thank you for following our work.
The details of our experimental environment are as follows:
Available memory is 502 GB
Available GPU are Tesla V100S (32GB) x 4

**Comment by lincgcg** [comment]
> 
Thanks for your reply, we have configured a similar configuration to yours:
Available memory is 503 GB
Available GPU are Tesla V100S (32GB) x 8
But we have some questions in the process of implementing Pre-process:

1. **Under your configuration, how long does it take to complete the second step in the pre-process?** , We've spent at least 24 hours now, but the program still hasn't finished running. We would also like you to tell us how long the other steps take to run.
2. We found that in the process of running the program(the second step in the pre-process), it only used nearly 502G of memory in the first few hours, but after about ten hours, the usage of the memory is only 10G-30G. **Did you encounter this situation？**

**Comment by linwhitehat** [comment]
> > 
> 
> Thanks for your reply, we have configured a similar configuration to yours: Available memory is 503 GB Available GPU are Tesla V100S (32GB) x 8 But we have some questions in the process of implementing Pre-process:
> 
> 1. **Under your configuration, how long does it take to complete the second step in the pre-process?** , We've spent at least 24 hours now, but the program still hasn't finished running. We would also like you to tell us how long the other steps take to run.
> 2. We found that in the process of running the program(the second step in the pre-process), it only used nearly 502G of memory in the first few hours, but after about ten hours, the usage of the memory is only 10G-30G. **Did you encounter this situation？**

1. The second step is to generate the pre-training dataset. The time cost of this step depends on the size of the corpora, and in our experiments, it took around 1-2 hours. I have checked and updated the codes, and suggest you replace the files in `uer/target/bert_target.py`  and `uer/utils/data.py` with the new one.
2. I have encountered a similar situation, and if this problem still exists after updating the code file, you can give feedback and we will share the generated pre-trained dataset.

**Comment by lincgcg** [comment]
> > > 
> > 
> > 
> > Thanks for your reply, we have configured a similar configuration to yours: Available memory is 503 GB Available GPU are Tesla V100S (32GB) x 8 But we have some questions in the process of implementing Pre-process:
> > 
> > 1. **Under your configuration, how long does it take to complete the second step in the pre-process?** , We've spent at least 24 hours now, but the program still hasn't finished running. We would also like you to tell us how long the other steps take to run.
> > 2. We found that in the process of running the program(the second step in the pre-process), it only used nearly 502G of memory in the first few hours, but after about ten hours, the usage of the memory is only 10G-30G. **Did you encounter this situation？**
> 
> 1. The second step is to generate the pre-training dataset. The time cost of this step depends on the size of the corpora, and in our experiments, it took around 1-2 hours. I have checked and updated the codes, and suggest you replace the files in `uer/target/bert_target.py`  and `uer/utils/data.py` with the new one.
> 2. I have encountered a similar situation, and if this problem still exists after updating the code file, you can give feedback and we will share the generated pre-trained dataset.

According to your suggestion, we successfully completed the second step in the pre-process, and got the dataset.pt file with a size of about 28G.
But unfortunately, we encountered some problems in the next task, and we tried many methods without success:

-  **In the third step of the pre-process**, we modified the file paths in the datasets/main.py file. We got the following results:

<img width="720" alt="Screen Shot 2022-04-01 at 21 01 32" src="https://user-images.githubusercontent.com/51119735/161268974-f0c54f40-6952-4d4b-8bda-fbe86ed9c03f.png">
<img width="1527" alt="Screen Shot 2022-04-01 at 20 39 32" src="https://user-images.githubusercontent.com/51119735/161268981-5c753c23-5b31-4be3-97ee-5907907ac08a.png">
We think it may be that there is no packet/splitcap/ under the path ../ET-BERT-main/datasets/cstnet-tls1.3/, if possible, please check if the code needs this file.

- **in pre-training**, We got the following results:
<img width="1549" alt="Screen Shot 2022-04-01 at 21 09 07" src="https://user-images.githubusercontent.com/51119735/161269943-50024b6f-7083-4d1a-8f1e-5b53d93bad9c.png">
<img width="1552" alt="Screen Shot 2022-04-01 at 21 09 49" src="https://user-images.githubusercontent.com/51119735/161270032-616dd820-c030-4f6e-ad26-9d641ab3ca96.png">
<img width="1569" alt="Screen Shot 2022-04-01 at 21 10 04" src="https://user-images.githubusercontent.com/51119735/161270082-6547c612-dc5b-437f-8c36-7ec792d17353.png">
We have no solution to this problem. Did you encounter this problem in the process of implementation? 

Looking forward to your reply!

**Comment by linwhitehat** [comment]
> > > > 
> > > 
> > > 
> > > Thanks for your reply, we have configured a similar configuration to yours: Available memory is 503 GB Available GPU are Tesla V100S (32GB) x 8 But we have some questions in the process of implementing Pre-process:
> > > 
> > > 1. **Under your configuration, how long does it take to complete the second step in the pre-process?** , We've spent at least 24 hours now, but the program still hasn't finished running. We would also like you to tell us how long the other steps take to run.
> > > 2. We found that in the process of running the program(the second step in the pre-process), it only used nearly 502G of memory in the first few hours, but after about ten hours, the usage of the memory is only 10G-30G. **Did you encounter this situation？**
> > 
> > 
> > 
> > 1. The second step is to generate the pre-training dataset. The time cost of this step depends on the size of the corpora, and in our experiments, it took around 1-2 hours. I have checked and updated the codes, and suggest you replace the files in `uer/target/bert_target.py`  and `uer/utils/data.py` with the new one.
> > 2. I have encountered a similar situation, and if this problem still exists after updating the code file, you can give feedback and we will share the generated pre-trained dataset.
> 
> According to your suggestion, we successfully completed the second step in the pre-process, and got the dataset.pt file with a size of about 28G. But unfortunately, we encountered some problems in the next task, and we tried many methods without success:
> 
> * **In the third step of the pre-process**, we modified the file paths in the datasets/main.py file. We got the following results:
> 
> <img alt="Screen Shot 2022-04-01 at 21 01 32" width="720" src="https://user-images.githubusercontent.com/51119735/161268974-f0c54f40-6952-4d4b-8bda-fbe86ed9c03f.png">
> 
> <img alt="Screen Shot 2022-04-01 at 20 39 32" width="1527" src="https://user-images.githubusercontent.com/51119735/161268981-5c753c23-5b31-4be3-97ee-5907907ac08a.png">
> 
> We think it may be that there is no packet/splitcap/ under the path ../ET-BERT-main/datasets/cstnet-tls1.3/, if possible, please check if the code needs this file.
> * **in pre-training**, We got the following results:
> 
> <img alt="Screen Shot 2022-04-01 at 21 09 07" width="1549" src="https://user-images.githubusercontent.com/51119735/161269943-50024b6f-7083-4d1a-8f1e-5b53d93bad9c.png">
> 
> <img alt="Screen Shot 2022-04-01 at 21 09 49" width="1552" src="https://user-images.githubusercontent.com/51119735/161270032-616dd820-c030-4f6e-ad26-9d641ab3ca96.png">
> 
> <img alt="Screen Shot 2022-04-01 at 21 10 04" width="1569" src="https://user-images.githubusercontent.com/51119735/161270082-6547c612-dc5b-437f-8c36-7ec792d17353.png">
> 
> We have no solution to this problem. Did you encounter this problem in the process of implementation?
> Looking forward to your reply!

Thanks for your feedback, we have updated the codes and readme to solve the problems.

**Comment by GuisengLiu** [comment]
Can you tell us your specific software configuration, for example, which vision of python? CUDA? torch?
Because we may met some problems  during the reproduction process.

**Comment by xxrelax** [comment]
Good discussion. How should I deal with this problem?
