### ISSUE TITLE
您好，我在用您处理数据的代码遇到一些问题？

### ISSUE THREAD

**Issue by Szthing** [linwhitehat/ET-BERT#30]
我在使用/data_process/main.py去对我电脑中的VPN-nonVPN数据集进行处理，用于微调。

我按照您的data_process/下的文档进行了如下操作，
将一下变量更改了
_category = 12 
pcap_path, dataset_save_path, samples, features, dataset_level = "F:\\shi\\dataset\\VPN-nonVPN", "F:\\shi\\dataset\\result\\", [5000], ["payload"], "packet"
 splitcap=True (line:54)
splitcap_finish =0
并在pcap_path目录下手动创建了splitcap文件夹，
然后运行 ，出现了以下报错，不知道是哪里的问题，想问一下您有什么办法吗？
![image](https://user-images.githubusercontent.com/37261209/190093271-680efe45-0b25-4fdd-8bd4-113fdaffde75.png)

**Comment by linwhitehat** [comment]
> 我在使用/data_process/main.py去对我电脑中的VPN-nonVPN数据集进行处理，用于微调。
> 
> 我按照您的data_process/下的文档进行了如下操作， 将一下变量更改了 _category = 12 pcap_path, dataset_save_path, samples, features, dataset_level = "F:\shi\dataset\VPN-nonVPN", "F:\shi\dataset\result\", [5000], ["payload"], "packet"  splitcap=True (line:54) splitcap_finish =0 并在pcap_path目录下手动创建了splitcap文件夹， 然后运行 ，出现了以下报错，不知道是哪里的问题，想问一下您有什么办法吗？ ![image](https://user-images.githubusercontent.com/37261209/190093271-680efe45-0b25-4fdd-8bd4-113fdaffde75.png)

在首次做split处理后，如果采样样本数据和实际切分后的样本数不符会导致采样报错。你可以试着在split处理后修改splitcap_finish为True，这样可以在采样前根据实际样本进行修改样本上限。

**Comment by Szthing** [comment]
> > 我在使用/data_process/main.py去对我电脑中的VPN-nonVPN数据集进行处理，用于微调。
> > 我按照您的data_process/下的文档进行了如下操作， 将一下变量更改了 _category = 12 pcap_path, dataset_save_path, samples, features, dataset_level = "F:\shi\dataset\VPN-nonVPN", "F:\shi\dataset\result", [5000], ["payload"], "packet"  splitcap=True (line:54) splitcap_finish =0 并在pcap_path目录下手动创建了splitcap文件夹， 然后运行 ，出现了以下报错，不知道是哪里的问题，想问一下您有什么办法吗？ ![image](https://user-images.githubusercontent.com/37261209/190093271-680efe45-0b25-4fdd-8bd4-113fdaffde75.png)
> 
> 在首次做split处理后，如果采样样本数据和实际切分后的样本数不符会导致采样报错。你可以试着在split处理后修改splitcap_finish为True，这样可以在采样前根据实际样本进行修改样本上限。



> > 我在使用/data_process/main.py去对我电脑中的VPN-nonVPN数据集进行处理，用于微调。
> > 我按照您的data_process/下的文档进行了如下操作， 将一下变量更改了 _category = 12 pcap_path, dataset_save_path, samples, features, dataset_level = "F:\shi\dataset\VPN-nonVPN", "F:\shi\dataset\result", [5000], ["payload"], "packet"  splitcap=True (line:54) splitcap_finish =0 并在pcap_path目录下手动创建了splitcap文件夹， 然后运行 ，出现了以下报错，不知道是哪里的问题，想问一下您有什么办法吗？ ![image](https://user-images.githubusercontent.com/37261209/190093271-680efe45-0b25-4fdd-8bd4-113fdaffde75.png)
> 
> 在首次做split处理后，如果采样样本数据和实际切分后的样本数不符会导致采样报错。你可以试着在split处理后修改splitcap_finish为True，这样可以在采样前根据实际样本进行修改样本上限。

非常感谢您的回答，我在尝试你提的办法后依旧无法解决这个问题，在我多次尝试，发现split处理时，并未执行对pcap进行切分 和创建splitcap的文件夹的操作， 从而导致这个BUG 的出现，但是我依旧不知道如何解决这个BUG，不知道您有什么解决方法吗

**Comment by linwhitehat** [comment]
@Szthing 如果没有做切分处理，建议你检查一下splicap工具是否正常调用，从你的描述只能看到最终没有数据切分结果，建议你将调用data_generation的split_cap函数进行调试查看。

**Comment by Szthing** [comment]
> @Szthing 如果没有做切分处理，建议你检查一下splicap工具是否正常调用，从你的描述只能看到最终没有数据切分结果，建议你将调用data_generation的split_cap函数进行调试查看。
您好，我的split_cap()函数可以正常运行，我在查看data_generation.py中generation函数中间位置多了一行return X,Y  导致下面的代码无法运行，从而无法进行split操作。 我将其注释后 ，代码就正常运转了。
     
       clean_dataset = 0    
        re_write = 0
        if clean_dataset:
                             ...
        elif re_write:
         return X,Y
          。。。
         return X,Y
