### ISSUE TITLE
about USTC-TFC datasets

### ISSUE THREAD

**Issue by lgbest123** [linwhitehat/ET-BERT#31]
你好。关于USTC-TFC2016数据集，我们按你提供的预处理代码进行flow预处理，很多类别数据个数为0，因为都小于5k被删除了，或者packet小于3个被过滤了。你们没有出现这种情况吗？

**Comment by linwhitehat** [comment]
> 你好。关于USTC-TFC2016数据集，我们按你提供的预处理代码进行flow预处理，很多类别数据个数为0，因为都小于5k被删除了，或者packet小于3个被过滤了。你们没有出现这种情况吗？

我在USTC以及其他一些类似botnet、cicmal等恶意流量数据处理中会遇到这种情况，此时需要调整这两个阈值来保留尽可能多的样本。

**Comment by lgbest123** [comment]
> > 你好。关于USTC-TFC2016数据集，我们按你提供的预处理代码进行flow预处理，很多类别数据个数为0，因为都小于5k被删除了，或者packet小于3个被过滤了。你们没有出现这种情况吗？
> 
> 我在USTC以及其他一些类似botnet、cicmal等恶意流量数据处理中会遇到这种情况，此时需要调整这两个阈值来保留尽可能多的样本。

感谢指导。代码中的这两个阈值适合哪些数据集啊？针对不同的下游任务，您这边有这两个阈值相关的经验分享吗

**Comment by linwhitehat** [comment]
> > > 你好。关于USTC-TFC2016数据集，我们按你提供的预处理代码进行flow预处理，很多类别数据个数为0，因为都小于5k被删除了，或者packet小于3个被过滤了。你们没有出现这种情况吗？
> > 
> > 
> > 我在USTC以及其他一些类似botnet、cicmal等恶意流量数据处理中会遇到这种情况，此时需要调整这两个阈值来保留尽可能多的样本。
> 
> 感谢指导。代码中的这两个阈值适合哪些数据集啊？针对不同的下游任务，您这边有这两个阈值相关的经验分享吗

代码预设的数值适合常规应用，不会存在大部分短流的情况。一般需要根据下游场景的流量情况来判断，建议是尽量不要太低，除非类似恶意流量这种情况。
