### ISSUE TITLE
作者您好，在用您的预处理代码生成预训练数据集的时候有些问题？

### ISSUE THREAD

**Issue by 18379835236** [linwhitehat/ET-BERT#32]
在按照data_process中的文档，利用dataset_generation.py对pcap文件进行处理的时候，并没有生成相应的txt文件，出现如下内容：
![image](https://user-images.githubusercontent.com/51084206/190545886-86599499-51a8-4265-ad66-8697efde3a69.png)
能麻烦您看看有什么问题吗？使用的pcap文件是IDS-2017中的Thursday-WorkingHours.pcap，麻烦您了

**Comment by linwhitehat** [comment]
> 在按照data_process中的文档，利用dataset_generation.py对pcap文件进行处理的时候，并没有生成相应的txt文件，出现如下内容： ![image](https://user-images.githubusercontent.com/51084206/190545886-86599499-51a8-4265-ad66-8697efde3a69.png) 能麻烦您看看有什么问题吗？使用的pcap文件是IDS-2017中的Thursday-WorkingHours.pcap，麻烦您了

你的报错是乱码，建议你先对已测试过的数据集进行验证是不是代码中的问题，不然可能问题来自你的数据集。

**Comment by linwhitehat** [comment]
> 感谢您的回复，请问您这边有未标记的流量数据集吗？我在项目中没有找到相关的下载地址，下载了您分享的CSTNET-TLS-1.3数据集，也不是PCAP格式的，所以我用的是您论文中提到的IDS-2017数据集。 ![image](https://user-images.githubusercontent.com/51084206/190599801-efc4cd71-5d36-4a80-812e-3585ae2c70cf.png)

因为预训练数据过大，没有办法上传。使用的公开数据集部分主要为ISCX-VPN数据，然后补充了其他数据集的一部分，你可以使用前者进行处理。
