### ISSUE TITLE
生成fine-tuning阶段数据部分时出现的问题

### ISSUE THREAD

**Issue by WBSLZF** [linwhitehat/ET-BERT#33]
作者你好请问一下为什么在生成fine-tuning阶段数据的时候，数据集上的有些token会出现4个字节即8个16进制，在生成token的时候不是不应该时bigram进行转换，即一个token是2个字节
![image](https://user-images.githubusercontent.com/60026863/190889813-3b72d5b5-d5dd-4b83-bce7-ccb15dd996b4.png)
![image](https://user-images.githubusercontent.com/60026863/190889841-b7f19fcf-7528-43f3-a204-2d930e173eed.png)
如红色划线部分

**Comment by linwhitehat** [comment]
> 作者你好请问一下为什么在生成fine-tuning阶段数据的时候，数据集上的有些token会出现4个字节即8个16进制，在生成token的时候不是不应该时bigram进行转换，即一个token是2个字节 ![image](https://user-images.githubusercontent.com/60026863/190889813-3b72d5b5-d5dd-4b83-bce7-ccb15dd996b4.png) ![image](https://user-images.githubusercontent.com/60026863/190889841-b7f19fcf-7528-43f3-a204-2d930e173eed.png) 如红色划线部分

这部分应该是在做flow级别的bigram切分组合时将尾部分隔符去除了，后续将修复这部分处理的代码

**Comment by WBSLZF** [comment]
作者大大我还有一个问题
![image](https://user-images.githubusercontent.com/60026863/191758388-9ceaba19-d930-4263-a5cf-736ff380545a.png)
就是data.decode(76:)我看你在其他回答里面说过是经过实验计算测得抹除IP，MAC，Port相关信息的长度，像76是咋根据实验做得，可以细锁一下嘛Orz

**Comment by WBSLZF** [comment]
作者大大还有一个问题，像是处理packet层面，也需要按照5元组划分后再算，还是直接处理未切割后的pcap

**Comment by linwhitehat** [comment]
> 作者大大我还有一个问题 ![image](https://user-images.githubusercontent.com/60026863/191758388-9ceaba19-d930-4263-a5cf-736ff380545a.png) 就是data.decode(76:)我看你在其他回答里面说过是经过实验计算测得抹除IP，MAC，Port相关信息的长度，像76是咋根据实验做得，可以细锁一下嘛Orz

这个是根据协议栈的一般规定进行确定的，选取范围是恰好在传输层的端口后进行报文存储。

**Comment by WBSLZF** [comment]
作者大大你好！我还有一些问题，比如对于流量的数据增强问题，你怎么看待

**Comment by WBSLZF** [comment]
作者大大你好，我还有一个问题，像是76个字节之后，那应该是把链路层头部，网络层头部，传输层头部，还有应用层的一部分都给去除了，传输层的一部分信息除了端口号之外的也算是噪音嘛 囧rz

**Comment by WBSLZF** [comment]
作者大大你好，我还有一个问题，像是76个字节之后，那应该是把链路层头部，网络层头部，传输层头部，还有应用层的一部分都给去除了，这个意思是传输层的一部分信息除了端口号之外的也算是噪音嘛 囧rz

**Comment by WBSLZF** [comment]
作者大大，比如像是链路层14个字节，网络层首部20个字节，传输层TCP20个字节，UDP8个字节，算起来，最多54个字节，像是76个字节是考虑到一些特殊情况，还是把应用层的一些部分给划分掉了

**Comment by linwhitehat** [comment]
> 作者大大，比如像是链路层14个字节，网络层首部20个字节，传输层TCP20个字节，UDP8个字节，算起来，最多54个字节，像是76个字节是考虑到一些特殊情况，还是把应用层的一些部分给划分掉了

这里的76我没有定义为字节数，而是实际序列长度

**Comment by WBSLZF** [comment]
好的，谢谢作者大大，大致明白了，太感谢了QWQ
