### ISSUE TITLE
你好作者，能不能提供多一些的经过预处理的数据集！

### ISSUE THREAD

**Issue by ctr555** [linwhitehat/ET-BERT#37]
这个预处理的时间较久，作者能否提供多一些经过预处理的数据集！

**Comment by linwhitehat** [comment]
> 这个预处理的时间较久，作者能否提供多一些经过预处理的数据集！

我们只能提供论文中提及的数据集，其他数据集暂时无法提供处理的帮助。

**Comment by Szthing** [comment]
> > 这个预处理的时间较久，作者能否提供多一些经过预处理的数据集！
> 
> 我们只能提供论文中提及的数据集，其他数据集暂时无法提供处理的帮助。

作者，您好，可以方便提供 SCX-Tor、Cross-Platform(Android) 、Cross-Platform(iOS)的packet和flow级别的数据集

**Comment by linwhitehat** [comment]
> > > 这个预处理的时间较久，作者能否提供多一些经过预处理的数据集！
> > 
> > 
> > 我们只能提供论文中提及的数据集，其他数据集暂时无法提供处理的帮助。
> 
> 作者，您好，可以方便提供 SCX-Tor、Cross-Platform(Android) 、Cross-Platform(iOS)的packet和flow级别的数据集

你好，可以使用已开源代码和公开数据集进行处理。
