### ISSUE TITLE
关于预处理数据的问题

### ISSUE THREAD

**Issue by JieJiemua** [linwhitehat/ET-BERT#39]
作者您好，在论文中，您最后给出的APP可视化的结果中，关于FileTransfer的有两个App分别是是FTPS和SFTP，可是在您提供的标签那张图中，这两个却是vpn通道下的，请问您用的是vpn通道下的FTPS和SFTP数据吗 ？这又是为什么呢？

**Comment by linwhitehat** [comment]
> 作者您好，在论文中，您最后给出的APP可视化的结果中，关于FileTransfer的有两个App分别是是FTPS和SFTP，可是在您提供的标签那张图中，这两个却是vpn通道下的，请问您用的是vpn通道下的FTPS和SFTP数据吗 ？这又是为什么呢？

你好，关于划分app的信息可以看一下这个回复 #28 ，在场景定义中便是确定在vpn流量中进行测试，只是根据场景粒度不同进行service和app划分。

**Comment by flttttttttt** [comment]
想问下大家有使用作业作者的代码自己预处理流量数据集嘛，我使用data-process中main函数预处理数据集一直出现问题。一直无法生成npy文件

**Comment by flttttttttt** [comment]
想问下大家使用作者的代码自己预处理流量数据集时有出现过什么问题吗，我使用data-process中main函数预处理数据集一直出现问题，一直无法生成npy文件。使用的也是ISCX-VPN-noVPN数据集进行预处理

**Comment by JieJiemua** [comment]
> 

谢谢您的回复，我看了您对于数据集的划分，那么论文中有关App分类的实验都是在vpn通道下进行的吗，可是数据集中只有ftps和sftp是加密的，其他的都不属于加密流量，如果想要知道其他加密app的分类结果是需要自己再生成数据集吗？还有请问为何要以burst的形式来表示呢？有什么好处吗？期待您的回复，谢谢！

**Comment by linwhitehat** [comment]
> > 
> 
> 谢谢您的回复，我看了您对于数据集的划分，那么论文中有关App分类的实验都是在vpn通道下进行的吗，可是数据集中只有ftps和sftp是加密的，其他的都不属于加密流量，如果想要知道其他加密app的分类结果是需要自己再生成数据集吗？还有请问为何要以burst的形式来表示呢？有什么好处吗？期待您的回复，谢谢！

app分类实验包括vpn和non-vpn，如果需要增加其他app实验可以补充数据集的；
选择burst是希望捕捉更紧凑的通信数据，也是观察到的一种通信特点，我们做了对比实验，选择burst形式对表征效果也更有帮助。
