### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Szthing** [linwhitehat/ET-BERT#40]
您好，首先非常感谢您的ET-Bert模型的开源工作，这对我学业有这巨大的帮助。 我有一事向您请求，您能否将flow-level 的VPN-service 、VPN -APP、USTC-TFC和CSTNET-TLS数据发给我，这对我意义重大。我的邮箱：814438025@qq.com
希望您能够答应我的请求。
再次感谢您，您对我的学业有着巨大的帮助。
祝您学业有成，生活顺利~

**Comment by linwhitehat** [comment]
> 您好，首先非常感谢您的ET-Bert模型的开源工作，这对我学业有这巨大的帮助。 我有一事向您请求，您能否将flow-level 的VPN-service 、VPN -APP、USTC-TFC和CSTNET-TLS数据发给我，这对我意义重大。我的邮箱：[814438025@qq.com](mailto:814438025@qq.com) 希望您能够答应我的请求。 再次感谢您，您对我的学业有着巨大的帮助。 祝您学业有成，生活顺利~

你好，感谢你的关注，这部分的数据可以使用开源代码进行生成和处理，如果需要处理好的，我们后续会上传云盘，方便更多需要的人下载。

**Comment by Szthing** [comment]
> Owner

非常感谢您的回复，希望您能在后续方便时上传flow-level的数据， 再次感谢您工作的开源。

**Comment by linwhitehat** [comment]
> > Owner
> 
> 非常感谢您的回复，希望您能在后续方便时上传flow-level的数据， 再次感谢您工作的开源。

已上传，请自行下载[Open-dataset](https://drive.google.com/drive/folders/1is609sosAdqf9YJAfwr72hBqM4OeNuZq?usp=sharing)

**Comment by Szthing** [comment]
> > > Owner
> > 
> > 
> > 非常感谢您的回复，希望您能在后续方便时上传flow-level的数据， 再次感谢您工作的开源。
> 
> 已上传，请自行下载[Open-dataset](https://drive.google.com/drive/folders/1is609sosAdqf9YJAfwr72hBqM4OeNuZq?usp=sharing)
太感谢您了
