### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by pemm-code** [linwhitehat/ET-BERT#43]
Hello, I would like to ask if the dataset you gave ISCX VPN, USTC_TFC public dataset is processed at the flow level or at the package level. Looking forward to your reply, thank you!

**Comment by linwhitehat** [comment]
> Hello, I would like to ask if the dataset you gave ISCX VPN, USTC_TFC public dataset is processed at the flow level or at the package level. Looking forward to your reply, thank you!

Hi, the processing is done at both levels, the flow-level directory is for flow-level data, while the one in the corresponding root directory is for packet-level.
