### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by HRH0517** [linwhitehat/ET-BERT#45]
![image](https://user-images.githubusercontent.com/57869555/209600789-32d39d56-1d89-46f5-82f7-5c6e7105b6fd.png)
这是什么问题呢

**Comment by linwhitehat** [comment]
> ![image](https://user-images.githubusercontent.com/57869555/209600789-32d39d56-1d89-46f5-82f7-5c6e7105b6fd.png) 这是什么问题呢

建议检查一下数据格式，看报错是加载数据异常
