### ISSUE TITLE
【fine-tuning】RuntimeError:The size of tensor a (128)must match the size of tensor b (768)at non-singleton dimension 2

### ISSUE THREAD

**Issue by GuisengLiu** [linwhitehat/ET-BERT#5]
Thank you for your work! When we follow the steps to fine-tuning the pretrained_model.bin, we meet a problem "RuntimeError:The size of tensor a (128)must match the size of tensor b (768)at non-singleton dimension 2"
[https://github.com/GuisengLiu/GitData/blob/master/1.png](url)
![image](https://github.com/GuisengLiu/GitData/blob/master/1.png)
The details of our experimental environment are as follows:
python 3.6
cudatoolkit 10.2.89
pytorch 1.10.2
Available GPU are Tesla K80 x 4

**Comment by linwhitehat** [comment]
> Thank you for your work! When we follow the steps to fine-tuning the pretrained_model.bin, we meet a problem "RuntimeError:The size of tensor a (128)must match the size of tensor b (768)at non-singleton dimension 2" [https://github.com/GuisengLiu/GitData/blob/master/1.png](url) ![image](https://github.com/GuisengLiu/GitData/blob/master/1.png) The details of our experimental environment are as follows: python 3.6 cudatoolkit 10.2.89 pytorch 1.10.2 Available GPU are Tesla K80 x 4

Thanks for following our work.
You can update the file `uer/layers/embeddings.py` to solve the problem.

**Comment by GuisengLiu** [comment]
Thanks for your replaying. After we updating whole project, the above issue has been solved. Another problem arises……
![image](https://github.com/GuisengLiu/GitData/blob/master/2.png)

**Comment by linwhitehat** [comment]
> Thanks for your replaying. After we updating whole project, the above issue has been solved. Another problem arises……"RuntimeError:CUDA error:CUBLAS_STATUS_NOT_INITIALIZED when calling cublasCreate(handle)" ![image](https://github.com/GuisengLiu/GitData/blob/master/2.png)

You can try to run with a smaller batch.
