### ISSUE TITLE
data set  update

### ISSUE THREAD

**Issue by cookie1024** [linwhitehat/ET-BERT#50]
[CSTNET-TLS 1.3](https://github.com/linwhitehat/ET-BERT/blob/main/CSTNET-TLS%201.3/readme.md)
The data set 'CSTNET-TLS 1.3' link is invalid. Could you update it? Thanks!

**Comment by Ziyan-22** [comment]
If possible, can you share the PCAP file as well? Thank you!

**Comment by linwhitehat** [comment]
> [CSTNET-TLS 1.3](https://github.com/linwhitehat/ET-BERT/blob/main/CSTNET-TLS%201.3/readme.md) The data set 'CSTNET-TLS 1.3' link is invalid. Could you update it? Thanks!

https://github.com/linwhitehat/ET-BERT/tree/main/datasets/CSTNET-TLS%201.3
