### ISSUE TITLE
Categories in the ISCX VPN-NonVPN data

### ISSUE THREAD

**Issue by satyandraguthula** [linwhitehat/ET-BERT#54]
Most of the data is self explanatory, but the facebook_video and skype_video pcaps were categorized as chat or streaming or voip (but voip should be audio only). Which categories were they put into?

**Comment by satyandraguthula** [comment]
I am trying to reproduce the result for ISCX-VPN-NonVPN data. I have taken your pretrained model. Provided the session split pcaps using https://github.com/shramos/pcap-splitter/blob/master/pcap_splitter/splitter.py as input for main.py in the data_process and changed _category appropriately. I am directing the same tsv files to the run_classifier.py using the same command you provided in the readme. But the results are not similar to the ones reported. Is there any step that I am missing?

**Comment by linwhitehat** [comment]
> Most of the data is self explanatory, but the facebook_video and skype_video pcaps were categorized as chat or streaming or voip (but voip should be audio only). Which categories were they put into?

Information about the categories can be found in the previous related issues like #27  as well as in the descriptions on the official website.
