### ISSUE TITLE
微调数据预处理如何生成tsv文件的问题

### ISSUE THREAD

**Issue by MiloGame** [linwhitehat/ET-BERT#58]
#8  如8号问题描述的，同问，看您写的readme里面的三条都是出现问题应该如何做，请问更具体一点的操作应该如何操作呢？比如第三步中pcap_path的路径还进行了变更，而且每一步都有这样的报错信息，
![image](https://user-images.githubusercontent.com/125568740/233261783-95d136e1-cf62-4722-9971-318f49c10204.png)
麻烦作者大大可以更加详细的给出如何生成tsv文件吗，谢谢

**Comment by linwhitehat** [comment]
> #8 如8号问题描述的，同问，看您写的readme里面的三条都是出现问题应该如何做，请问更具体一点的操作应该如何操作呢？比如第三步中pcap_path的路径还进行了变更，而且每一步都有这样的报错信息， ![image](https://user-images.githubusercontent.com/125568740/233261783-95d136e1-cf62-4722-9971-318f49c10204.png) 麻烦作者大大可以更加详细的给出如何生成tsv文件吗，谢谢

这里生成文件是两个环节，第一步是你图中的流量切分，你可以查看是否有具体的切分流量存储，之后第二步需要进行数据提取和构造，这一步才会生成tsv文件。

**Comment by KyrieIrvingmvp** [comment]
作者您好，请问您提到的数据提取和构造分别对应哪个文件，我在自己通过pcap生成tsv文件的过程中，执行完流量切分后是有切分流量存储，再拿切分流量去执行data_process文件夹下的main.py，只得到了一个json文件，请问如何得到tsv文件。另外问一下data_generation得到的encryptd_burst.txt文件有什么作用。（抱歉，确实技术小白，希望作者可以稍微讲解细致一点，thx！）

**Comment by linwhitehat** [comment]
> 作者您好，请问您提到的数据提取和构造分别对应哪个文件，我在自己通过pcap生成tsv文件的过程中，执行完流量切分后是有切分流量存储，再拿切分流量去执行data_process文件夹下的main.py，只得到了一个json文件，请问如何得到tsv文件。另外问一下data_generation得到的encryptd_burst.txt文件有什么作用。（抱歉，确实技术小白，希望作者可以稍微讲解细致一点，thx！）

tsv文件写入是main下的[这部分代码](https://github.com/linwhitehat/ET-BERT/blob/25709b3eca4058910cc182ccc50275fe1ab75e62/data_process/main.py#L164C2-L164C2)处理，你可以查看一下是否有正常执行。burst的数据是用于预训练阶段使用的，具体作用可详见论文。
