### ISSUE TITLE
关于微调数据集把5000个samples都划分到同一类里的问题

### ISSUE THREAD

**Issue by m1homo** [linwhitehat/ET-BERT#59]
如题请问作者大大，为什么按照操作处理完之后会是这样的结果呀。也没有报错
<img width="460" alt="image" src="https://user-images.githubusercontent.com/125568740/233522805-9b7170e6-1319-4508-91d2-5508d8bdfbb2.png">
<img width="320" alt="image" src="https://user-images.githubusercontent.com/125568740/233522840-ce646720-9d0c-403b-abfa-0b9faa67f7fd.png">

**Comment by linwhitehat** [comment]
> 如题请问作者大大，为什么按照操作处理完之后会是这样的结果呀。也没有报错 <img alt="image" width="460" src="https://user-images.githubusercontent.com/125568740/233522805-9b7170e6-1319-4508-91d2-5508d8bdfbb2.png"> <img alt="image" width="320" src="https://user-images.githubusercontent.com/125568740/233522840-ce646720-9d0c-403b-abfa-0b9faa67f7fd.png">

你的实际标签数据和预期标签数据之间不对等导致的。

**Comment by m1homo** [comment]
好的我再检查一下，我用的是您论文里提到的ISPX-VPN数据集
