### ISSUE TITLE
[Fine-tuning Problem] No module named 'uer'

### ISSUE THREAD

**Issue by JieJayCao** [linwhitehat/ET-BERT#6]
Hello, when I am reproducing your fine tuning work, I keep reporting the following error, I don't know how to solve it, I am looking forward to your answer.

```
Traceback (most recent call last):
  File "fine-tuning/run_classifier.py", line 8, in <module>
    from uer.layers import *
ModuleNotFoundError: No module named 'uer'
```

**Comment by GuisengLiu** [comment]
Looking carefully at the root directory，there is a directory named 'uer'
[](https://github.com/linwhitehat/ET-BERT/tree/main/uer)

**Comment by linwhitehat** [comment]
> Hello, when I am reproducing your fine tuning work, I keep reporting the following error, I don't know how to solve it, I am looking forward to your answer.
> 
> ```
> Traceback (most recent call last):
>   File "fine-tuning/run_classifier.py", line 8, in <module>
>     from uer.layers import *
> ModuleNotFoundError: No module named 'uer'
> ```

Please check the files and correct the path in the local.

**Comment by 123Sun556** [comment]
> Hello, when I am reproducing your fine tuning work, I keep reporting the following error, I don't know how to solve it, I am looking forward to your answer.
> 
> ```
> Traceback (most recent call last):
>   File "fine-tuning/run_classifier.py", line 8, in <module>
>     from uer.layers import *
> ModuleNotFoundError: No module named 'uer'
> ```

在当前目录右键make_directory as-->Sources Root
