### ISSUE TITLE
直接下载的处理好的数据集进行微调时，发现缺失了一个关键文件

### ISSUE THREAD

**Issue by m1homo** [linwhitehat/ET-BERT#60]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/125568740/233618215-ab006f5b-ec5f-408d-b49e-f567ad4e9c47.png">
<img width="441" alt="image" src="https://user-images.githubusercontent.com/125568740/233618264-53c9587d-4ccf-4757-b6ee-a0742ac917a5.png">
r如题请问作者大大这个文件从哪里下载啊？我没在readme里面发现相关说明

**Comment by linwhitehat** [comment]
> <img alt="image" width="487" src="https://user-images.githubusercontent.com/125568740/233618215-ab006f5b-ec5f-408d-b49e-f567ad4e9c47.png">
> 
> <img alt="image" width="441" src="https://user-images.githubusercontent.com/125568740/233618264-53c9587d-4ccf-4757-b6ee-a0742ac917a5.png">
> 
> r如题请问作者大大这个文件从哪里下载啊？我没在readme里面发现相关说明

这个是用于结果判别的辅助文件，可以自行生成。

**Comment by m1homo** [comment]
> > <img alt="image" width="487" src="https://user-images.githubusercontent.com/125568740/233618215-ab006f5b-ec5f-408d-b49e-f567ad4e9c47.png">
> > <img alt="image" width="441" src="https://user-images.githubusercontent.com/125568740/233618264-53c9587d-4ccf-4757-b6ee-a0742ac917a5.png">
> > r如题请问作者大大这个文件从哪里下载啊？我没在readme里面发现相关说明
> 
> 这个是用于结果判别的辅助文件，可以自行生成。

好的好的，非常感谢。
