### ISSUE TITLE
VRAM needed for finetuning

### ISSUE THREAD

**Issue by miqsoft** [linwhitehat/ET-BERT#63]
Hey,

Since in the requirements the GPU: Tesla V100S is mentied I'm wondering if this is meant for training the model or for finetuning.
Or in other words, is it also possible to do the finetuning on a graphic card with 12GB or so.

Greetings,
Michael

**Comment by zxxcjy123** [comment]
微调够的

**Comment by zxxcjy123** [comment]
微调阶段batch_size32大概需要8-9G显存
