### ISSUE TITLE
Data labeling?

### ISSUE THREAD

**Issue by aaminahassan** [linwhitehat/ET-BERT#65]
How to label the data after downloading from [this ](URL), as mentioned in readme file.
[URL](https://drive.google.com/drive/folders/1JSsYmevkxQFanoKOi_i1ooA6pH3s9sDr)

I converted the .npy extension files to csv and got the following error:

```
label = int(line[columns["label"]])File "/fine-tuning/run_classifier.py", line 77, in count_labels_num
    label = int(line[columns["label"]])
KeyError: 'label'
```
Tell us the clear method to continue after downloading datasets.

**Comment by Codebilibili** [comment]
> How to label the data after downloading from [this ](URL), as mentioned in readme file. [URL](https://drive.google.com/drive/folders/1JSsYmevkxQFanoKOi_i1ooA6pH3s9sDr)
> 
> I converted the .npy extension files to csv and got the following error:
> 
> ```
> label = int(line[columns["label"]])File "/fine-tuning/run_classifier.py", line 77, in count_labels_num
>     label = int(line[columns["label"]])
> KeyError: 'label'
> ```
> 
> Tell us the clear method to continue after downloading datasets.

I had a similar problem. Have you solved it yet? How did you fix it?

**Comment by linwhitehat** [comment]
The label info is from the files named y*.npy. This part needs to associate the label data before generating the tsv file.
