### ISSUE TITLE
关于微调后模型泛化能力的问题

### ISSUE THREAD

**Issue by sdz614** [linwhitehat/ET-BERT#66]
在微调任务中，我使用ISCXVPN2016数据集中各类别的一部分pcap进行训练和测试，分类效果很好，然后使用另一部分同类别的pcap测试训练好的模型，分类效果很差，请问是什么原因

**Comment by Kaleidoscope-arch** [comment]
> 在微调任务中，我使用ISCXVPN2016数据集中各类别的一部分pcap进行训练和测试，分类效果很好，然后使用另一部分同类别的pcap测试训练好的模型，分类效果很差，请问是什么原因

ISCX数据集本身存在相当大的偶然性和非无偏性，只要你数据集划分（挑选）的好，简单的三层mlp都可以上90%+的精度
