### ISSUE TITLE
CrossPlatForm数据集的问题

### ISSUE THREAD

**Issue by WBSLZF** [linwhitehat/ET-BERT#67]
您好作者，请问下在复现您相关工作时对于CrossPlatForm数据集的安卓应用分类下，切分训练集验证集和测试集，发现有些样本太少了，低于10个样本，根本无法按照8：1：1进行切分，在这部分数据，作者是如何处理的呢

**Comment by linwhitehat** [comment]
> 您好作者，请问下在复现您相关工作时对于CrossPlatForm数据集的安卓应用分类下，切分训练集验证集和测试集，发现有些样本太少了，低于10个样本，根本无法按照8：1：1进行切分，在这部分数据，作者是如何处理的呢

我们没有采用全量的CP数据，对于这部分极少数样本的应用被排除了。
