### ISSUE TITLE
Have you removed bidirectional IP and port information and protocol information to reduce the impact of packet headers? (e.g. remove 5-tuples)

### ISSUE THREAD

**Issue by dbzzang-ping** [linwhitehat/ET-BERT#70]
I am reading your paper with great interest.

In Section 4.1.2 data preprocessing, did you remove bidirectional IP address and port values, as well as protocol information, to reduce the impact of packet headers? (e.g., removing 5-tuples)

Please explain in detail ‘removing the protocol port of the Ethernet header, IP header, and TCP header’.
(For example, remove IP source and destination addresses, TCP source and destination port information, etc.)

**Comment by linwhitehat** [comment]
> I am reading your paper with great interest.
> 
> In Section 4.1.2 data preprocessing, did you remove bidirectional IP address and port values, as well as protocol information, to reduce the impact of packet headers? (e.g., removing 5-tuples)
> 
> Please explain in detail ‘removing the protocol port of the Ethernet header, IP header, and TCP header’. (For example, remove IP source and destination addresses, TCP source and destination port information, etc.)

Yes, we did this part of the header data removal, including these fields that you mentioned, and they come from the network layer and the transport layer.
