### ISSUE TITLE
How to generate .tsv files

### ISSUE THREAD

**Issue by aaminahassan** [linwhitehat/ET-BERT#72]
Dear Team , I need help in generating valid_dataset.tsv, *.tsv files. I have downloaded TLS dataset. and donot know what to do next, how to label data and generate json.

**Comment by linwhitehat** [comment]
> Dear Team , I need help in generating valid_dataset.tsv, *.tsv files. I have downloaded TLS dataset. and donot know what to do next, how to label data and generate json.

In general, the labeling of data is something that should be done during your data collection session, and the dataset normally contains labeling information.
Generating tsv files can then be handled by referring to the [main.py](https://github.com/linwhitehat/ET-BERT/blob/main/data_process/main.py#L164C2-L164C2) file.

**Comment by tyyyy18** [comment]
Use [main.py](https://github.com/linwhitehat/ET-BERT/blob/main/data_process/main.py#L164C2-L164C2)file to construct the downloaded dataset. You need to change the path such as "I:/" to your own path and place the downloaded dataset under ".. CSTNET-TLS 1.3 \ packet \ \ result \"
