### ISSUE TITLE
关于用于预训练的语料问题？

### ISSUE THREAD

**Issue by AIIeinsein** [linwhitehat/ET-BERT#73]
微调数据集的多少比例用来训练预训练模型？

**Comment by AIIeinsein** [comment]
我傻逼了， 文中选用的好像是最多500flow和5000packet作为微调数据集，然后8:1:1进行切分微调，后变为了验证few slot 采用数据10% 20% 40% 进行的微调

**Comment by linwhitehat** [comment]
> 微调数据集的多少比例用来训练预训练模型？

你好，感谢对我们的工作的关注，实验设置部分在论文中有介绍。在flow和packet下的设置规模分别是500和5000的每类上限，按照8-1-1进行微调。
