### ISSUE TITLE
dataprogress

### ISSUE THREAD

**Issue by 1195986182** [linwhitehat/ET-BERT#74]
请问，我希望传入一个pcap文件，然后将文件内容全转换为无标签的数据方式，然后使用模型预测标签，应该如何处理

**Comment by linwhitehat** [comment]
> 请问，我希望传入一个pcap文件，然后将文件内容全转换为无标签的数据方式，然后使用模型预测标签，应该如何处理

pcap文件转换数据的方式可以参考[main.py](https://github.com/linwhitehat/ET-BERT/blob/main/data_process/main.py#L164C2-L164C2)中的数据处理，预测标签可以参考[模型推理部分](https://github.com/linwhitehat/ET-BERT/tree/main?tab=readme-ov-file#using-et-bert)
