### ISSUE TITLE
请问ET-BERT对于纯数据流能进行识别和分类吗

### ISSUE THREAD

**Issue by alderpaw** [linwhitehat/ET-BERT#76]
作者你好，请问在只有数据流的情况下，比如去除TLS 1.3中server hello等握手阶段的报文，或者FTP数据流，ET-BERT模型能够做到正确的识别吗？还是必须要依赖于一些控制流的信息？

**Comment by linwhitehat** [comment]
> 作者你好，请问在只有数据流的情况下，比如去除TLS 1.3中server hello等握手阶段的报文，或者FTP数据流，ET-BERT模型能够做到正确的识别吗？还是必须要依赖于一些控制流的信息？

你好，这个工作还是有依赖控制流信息的，完全的数据流，尤其是完全加密后是会有明显的性能损失。但是对于仅去除握手阶段信息，我们只验证了去除client hello的握手信息下并未影响性能。
