### ISSUE TITLE
uer utils中的misc.py问题

### ISSUE THREAD

**Issue by plutolive** [linwhitehat/ET-BERT#78]
data = f.read(2^20)是否应该是data = f.read(2**20)
还有一个问题，model下的encrypted_vocab.txt是哪里生成的？是用vocab_process下的main.py吗？encrypted_vocab.txt是否与corpora下的encrypted_vocab_all.txt类似的，只是通过不同的burst文件生成的？

**Comment by linwhitehat** [comment]
> data = f.read(2^20)是否应该是data = f.read(2**20) 还有一个问题，model下的encrypted_vocab.txt是哪里生成的？是用vocab_process下的main.py吗？encrypted_vocab.txt是否与corpora下的encrypted_vocab_all.txt类似的，只是通过不同的burst文件生成的？

你好，感谢对我们工作的关注。读取代码确实需要修改，我们将更新最新的代码。
encrypted_vocab.txt和encrypted_vocab_all.txt是类似的，使用vocab_process下的main.py进行字典生成。
