### ISSUE TITLE
Error in data processing in VPN dataset

### ISSUE THREAD

**Issue by pb1069** [linwhitehat/ET-BERT#79]
We tested your model using the ISCX VPN 2016 dataset. The ISCX VPN 2016 dataset is divided into "VPN" and "nonVPN" categories. Within the "VPN" category, all applications' pcaps except for voipbuster contain raw packet layer data, with no ethernet headers.

In your paper, you mentioned removing the IP header and removing the source port and destination port from the TCP header. <= Has this been accurately implemented in your source code?

We noticed that some TCP packets in the numpy extension file you provided had an additional removal of the size of the ethernet header (14 bytes). Please verify and provide a response.

![error_in_dataprocess(in_vpn2016)](https://github.com/linwhitehat/ET-BERT/assets/33802391/435cc5a5-e67d-461a-8a8a-e0be97baf2c4)

**Comment by mzubair31102** [comment]
Please help Error: Traceback (most recent call last):
Error:   File "/content/drive/My Drive/BERT/ET-BERT/fine-tuning/run_classifier.py", line 8, in <module>
Error:     from uer.layers import *
Error: ModuleNotFoundError: No module named 'uer'

**Comment by pb1069** [comment]
> Please help Error: Traceback (most recent call last): Error: File "/content/drive/My Drive/BERT/ET-BERT/fine-tuning/run_classifier.py", line 8, in Error: from uer.layers import * Error: ModuleNotFoundError: No module named 'uer'

May be.. You can solve this error though jusy copying uer(folder) to fine-tuning(folder).

**Comment by pb1069** [comment]
> Please help Error: Traceback (most recent call last): Error: File "/content/drive/My Drive/BERT/ET-BERT/fine-tuning/run_classifier.py", line 8, in Error: from uer.layers import * Error: ModuleNotFoundError: No module named 'uer'

![Uploading Screenshot_20240820_024559_Chrome.jpg…]()

**Comment by linwhitehat** [comment]
> We tested your model using the ISCX VPN 2016 dataset. The ISCX VPN 2016 dataset is divided into "VPN" and "nonVPN" categories. Within the "VPN" category, all applications' pcaps except for voipbuster contain raw packet layer data, with no ethernet headers.
> 
> In your paper, you mentioned removing the IP header and removing the source port and destination port from the TCP header. <= Has this been accurately implemented in your source code?
> 
> We noticed that some TCP packets in the numpy extension file you provided had an additional removal of the size of the ethernet header (14 bytes). Please verify and provide a response.
> 
> ![error_in_dataprocess(in_vpn2016)](https://private-user-images.githubusercontent.com/33802391/315297715-435cc5a5-e67d-461a-8a8a-e0be97baf2c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODcyMDEsIm5iZiI6MTcyNDk4NjkwMSwicGF0aCI6Ii8zMzgwMjM5MS8zMTUyOTc3MTUtNDM1Y2M1YTUtZTY3ZC00NjFhLThhOGEtZTBiZTk3YmFmMmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDAzMDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzM1MDRkYTM1ZWVkNDUyNDVlMDFhZTEwZjdhNDc0YWQ2OGU0OTkwMjdjNmQ2Njk4YTY0MmRmODU2ODBkYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.perg3YnrkFqO5nN39sRFdz49BSthAfuT59axStVYPD0)

Thank you for your interest in our work. In section 4.1.2 Data Pre-processing in the paper, we describe the removal of content containing the Ethernet header.

**Comment by linwhitehat** [comment]
> Please help Error: Traceback (most recent call last): Error: File "/content/drive/My Drive/BERT/ET-BERT/fine-tuning/run_classifier.py", line 8, in Error: from uer.layers import * Error: ModuleNotFoundError: No module named 'uer'

Thanks for your question. You can solve this error though just copying uer(folder; you can find it in root directory) to fine-tuning(folder). Thanks for the answer from @pb1069 .

> > Please help Error: Traceback (most recent call last): Error: File "/content/drive/My Drive/BERT/ET-BERT/fine-tuning/run_classifier.py", line 8, in Error: from uer.layers import * Error: ModuleNotFoundError: No module named 'uer'
> 
> May be.. You can solve this error though just copying uer(folder; you can find it in root directory) to fine-tuning(folder).
