### ISSUE TITLE
语料库生成问题

### ISSUE THREAD

**Issue by Chenxin2000** [linwhitehat/ET-BERT#82]
问一下语料库生成需要多少pcap文件，只需要一个大的pcap文件就够，还是需要所有要跑的pcap文件

**Comment by linwhitehat** [comment]
> 问一下语料库生成需要多少pcap文件，只需要一个大的pcap文件就够，还是需要所有要跑的pcap文件

你好，感谢对我们工作的关注。语料数据的构建我们使用了30GB的原始流量，具体描述在论文中有介绍。和下游任务使用的pcap文件没有直接关联。
