### ISSUE TITLE
Missing prediction.tsv file

### ISSUE THREAD

**Issue by KievTrung** [linwhitehat/ET-BERT#84]
In cstnet-tls1.3_packet/packet directory, there is nolable_test_dataset.tsv but there's no label, i suspect there's a file containing labels for that since there is prediction.tsv in this command:
`
python3 inference/run_classifier_infer.py --load_model_path models/finetuned_model.bin 
                                          --vocab_path models/encryptd_vocab.txt 
                                          --test_path datasets/cstnet-tls1.3/packet/nolabel_test_dataset.tsv 
                                          --prediction_path datasets/cstnet-tls1.3/packet/prediction.tsv 
                                          --labels_num 120 
                                          --embedding word_pos_seg --encoder transformer --mask fully_visible
`

**Comment by 5Fence** [comment]
Hello, may I ask how you solved this problem?

**Comment by KievTrung** [comment]
Actually, the output of the nolabel_test_dataset.tsv is the prediction.tsv, so the model is basically predicting the nolabel file and store the result in a prediction.tsv file

**Comment by 5Fence** [comment]
Oh, I see. Thank you very much for your response.

**Comment by Kaleidoscope-arch** [comment]
> Actually, the output of the nolabel_test_dataset.tsv is the prediction.tsv, so the model is basically predicting the nolabel file and store the result in a prediction.tsv file

if so, then how can we figure out the accuracy of such non-label data?

**Comment by KievTrung** [comment]
well, i think such non labels are not used for measuring accuracy, but for the purpose of predicting, since they already tested and trained it in the previous stage
