### ISSUE TITLE
对于制作fine-tunning数据集的困惑

### ISSUE THREAD

**Issue by JerryWangAccount** [linwhitehat/ET-BERT#86]
作者您好，我尝试通过您提供的代码来制作fine-tunning数据集，我根据 https://github.com/linwhitehat/ET-BERT/tree/main/data_process 的描述，运行main.py，发现当设置splitcap=True (line:54) 的时候，main.py会报错，最终会生成一个空的dataset.json，因为源码中main.py会调用dataset_generation.py中的generation函数，该函数的459行，有一个代码逻辑是 if splitcap为True，则跳过循环，貌似这样就不会进行后续的操作，使得生成空的dataset.json。

是否https://github.com/linwhitehat/ET-BERT/tree/main/data_process 的描述有误，或者此处的代码逻辑有混淆的地方？

希望得到您的回复，谢谢。

**Comment by linwhitehat** [comment]
> 作者您好，我尝试通过您提供的代码来制作fine-tunning数据集，我根据 https://github.com/linwhitehat/ET-BERT/tree/main/data_process 的描述，运行main.py，发现当设置splitcap=True (line:54) 的时候，main.py会报错，最终会生成一个空的dataset.json，因为源码中main.py会调用dataset_generation.py中的generation函数，该函数的459行，有一个代码逻辑是 if splitcap为True，则跳过循环，貌似这样就不会进行后续的操作，使得生成空的dataset.json。
> 
> 是否https://github.com/linwhitehat/ET-BERT/tree/main/data_process 的描述有误，或者此处的代码逻辑有混淆的地方？
> 
> 希望得到您的回复，谢谢。

如果设置为True需要再改为False后执行，生成空是因为读取的数据来源地址不正确，需要更新为切分好数据的地址。

**Comment by JerryWangAccount** [comment]
您好，我想确认一下这个地方的具体步骤，我采用的步骤如下 （我参考了https://github.com/linwhitehat/ET-BERT/tree/main/data_process）：
1. 设置 pcap_path, dataset_save_path, samples, features, dataset_level
当只进行split raw pacp文件的时候，pcap_path 我设置的即为原始的pcap所在的文件夹

2. 设置splitcap=True，运行main.py 我发现代码会切分pcap_path所在路径的raw pacp，并保存到pcap_path/splitcap文件夹下

但我困惑的点是，此处，代码就会生成一个空的dataset.json（运行main.py即会产生，并导致后续报错）

希望您解答一下，谢谢！
