### ISSUE TITLE
4090单卡微调提示Cuda Out of memory

### ISSUE THREAD

**Issue by MiloSciA** [linwhitehat/ET-BERT#89]
大佬您好，我看您的论文里面写了微调的时候单卡就可以，想问一下单卡是选用哪个型号呀，我用4090单卡微调爆显存了ORZ

**Comment by linwhitehat** [comment]
> 大佬您好，我看您的论文里面写了微调的时候单卡就可以，想问一下单卡是选用哪个型号呀，我用4090单卡微调爆显存了ORZ

你好，我们使用的是单卡 Tesla V100S进行微调，在论文的环境设置中有介绍。
