### ISSUE TITLE
About the packet string truncation in pre-training.

### ISSUE THREAD

**Issue by qqr1110** [linwhitehat/ET-BERT#9]
> Hello, I want to pre-train the model from scratch. In the first step of "Repeoduce ET-BERT",in "data_preprocess/main.py",I haven't found how to split pcap file or how to generate BURST in this process.The code directly calls the preprocess function to process the PCAP files and then generates the corpus txt files.
> 
> By further reading the code,I found that the "pretrain_dataset_generation" function in "datasets/dataset_generation.py" should be the pre-training data processing process, which consists of pcap files processing and split, BURST feature generation, etc. However, in "get_burst_feature" function called in the BURST generation part, I did not see how to remove the source IP and target IP of the packets and the TCP source and target port, which should be different from the paper described in 4.1.2.
> 
> On the other hand,line 64 of "data_preprocess/main.py" removes the Ethernet and IP headers, but there seems it doesn't remove the tcp's source and destination port numbers. So what I want to know is,How do I construct pre-training data for any given pcap files.
> 
> Thank you.

Thanks for your interest in our work.
The data_preprocess directory is in fact what builds the vocabulary table, and I have updated the directory name.
The dataset_generation.py is the key code for data preprocessing, regarding the removal of fields such as IP and port on lines 151, 307 and 313. Also in the "data_preprocess/main.py" you mentioned, the corresponding processing is done and the removal content contains the IP and port information. The truncation location in our experiment is 76, which already contains MAC, IP, and TCP port information.

For the processing of arbitrary PCAP files, I will subsequently update a README file to introduce it independently, as the process is not shown fluently in the code.

_Originally posted by @linwhitehat in https://github.com/linwhitehat/ET-BERT/issues/7#issuecomment-1090410579_

I have read your updated code, and I still have some doubts:

1.In "vocab_process/main.py", line 64, the code is 'words.decode()[68:]'. Should it be 'words.decode()[76:]'? because the first 34 bytes of one packet do not contain the source and destination port numbers of TCP.

2.In the pre-training data processing stage, in line 111 of "data_process/dataset_generation.py/get_burst_feature()", the code is 'Packet_string = data.decode()[: 2 * payload_len]'. Should it be 'Packet_string = data.decode()[76: 76+2 * payload_len]'?Because the first 38 bytes need to be truncated.

Thank you.

**Comment by linwhitehat** [comment]
> > Hello, I want to pre-train the model from scratch. In the first step of "Repeoduce ET-BERT",in "data_preprocess/main.py",I haven't found how to split pcap file or how to generate BURST in this process.The code directly calls the preprocess function to process the PCAP files and then generates the corpus txt files.
> > By further reading the code,I found that the "pretrain_dataset_generation" function in "datasets/dataset_generation.py" should be the pre-training data processing process, which consists of pcap files processing and split, BURST feature generation, etc. However, in "get_burst_feature" function called in the BURST generation part, I did not see how to remove the source IP and target IP of the packets and the TCP source and target port, which should be different from the paper described in 4.1.2.
> > On the other hand,line 64 of "data_preprocess/main.py" removes the Ethernet and IP headers, but there seems it doesn't remove the tcp's source and destination port numbers. So what I want to know is,How do I construct pre-training data for any given pcap files.
> > Thank you.
> 
> Thanks for your interest in our work. The data_preprocess directory is in fact what builds the vocabulary table, and I have updated the directory name. The dataset_generation.py is the key code for data preprocessing, regarding the removal of fields such as IP and port on lines 151, 307 and 313. Also in the "data_preprocess/main.py" you mentioned, the corresponding processing is done and the removal content contains the IP and port information. The truncation location in our experiment is 76, which already contains MAC, IP, and TCP port information.
> 
> For the processing of arbitrary PCAP files, I will subsequently update a README file to introduce it independently, as the process is not shown fluently in the code.
> 
> _Originally posted by @linwhitehat in [#7 (comment)](https://github.com/linwhitehat/ET-BERT/issues/7#issuecomment-1090410579)_
> 
> I have read your updated code, and I still have some doubts:
> 
> 1.In "vocab_process/main.py", line 64, the code is 'words.decode()[68:]'. Should it be 'words.decode()[76:]'? because the first 34 bytes of one packet do not contain the source and destination port numbers of TCP.
> 
> 2.In the pre-training data processing stage, in line 111 of "data_process/dataset_generation.py/get_burst_feature()", the code is 'Packet_string = data.decode()[: 2 * payload_len]'. Should it be 'Packet_string = data.decode()[76: 76+2 * payload_len]'?Because the first 38 bytes need to be truncated.
> 
> Thank you.

Thank you for your feedback on the problem in the code.
1. I have fixed the code accordingly.
2. The pre-training phase is self-supervised learning and the data used is unlabeled. Then we care more about the truncated processing of data in the downstream supervised learning phase.

**Comment by qqr1110** [comment]
Ok, thanks for your reply. 
These 38 bytes are skipped when building the BPE, the same goes for the fine-tune's data preprocessing. But these bytes are not skipped in the pre-training phase. So I'm a little confused, maybe I missed something.

Thank you.

**Comment by linwhitehat** [comment]
> Ok, thanks for your reply. These 38 bytes are skipped when building the BPE, the same goes for the fine-tune's data preprocessing. But these bytes are not skipped in the pre-training phase. So I'm a little confused, maybe I missed something.
> 
> Thank you.

Thanks for your question. The same truncation can be done in the pre-training phase, but I think they do not have a negative impact and thus the choice can be freer. I hope you can feedback here when the test found problems, and I will verify and fix the error.

**Comment by shamoqianting** [comment]
> 

I also have same doubt about the code 'Packet_string = data.decode()[: 2 * payload_len]' in get_burst_feature(). It seems that the payload_len is set to be 64. why it's not the whole length of the packet? Does the number 64 have some particular meaning here ?

**Comment by linwhitehat** [comment]
> > 
> 
> I also have same doubt about the code 'Packet_string = data.decode()[: 2 * payload_len]' in get_burst_feature(). It seems that the payload_len is set to be 64. why it's not the whole length of the packet? Does the number 64 have some particular meaning here ?

Thank you for your question. Since the pre-trained model is very large and does not learn well for longer sequences, we set that length in the hope that the burst input can contain multiple packet contents, which prevents the input data from being concentrated in only a single packet.

**Comment by 11asdad** [comment]
> > Ok, thanks for your reply. These 38 bytes are skipped when building the BPE, the same goes for the fine-tune's data preprocessing. But these bytes are not skipped in the pre-training phase. So I'm a little confused, maybe I missed something.
> > Thank you.
> 
> Thanks for your question. The same truncation can be done in the pre-training phase, but I think they do not have a negative impact and thus the choice can be freer. I hope you can feedback here when the test found problems, and I will verify and fix the error.

你好，我有点没明白这里，经过了finetuning的三个data_process的步骤后生成的npy文件中的payload，在后续的任务中还会被进一步截断吗？还是npy文件中的就是模型最终的学习内容
Hello,I  am also confused about this.Does the data in npy files generated by the data_process/main.py still will be truncated?Or it already is the real thing that model study from?

**Comment by linwhitehat** [comment]
> > > Ok, thanks for your reply. These 38 bytes are skipped when building the BPE, the same goes for the fine-tune's data preprocessing. But these bytes are not skipped in the pre-training phase. So I'm a little confused, maybe I missed something.
> > > Thank you.
> > 
> > 
> > Thanks for your question. The same truncation can be done in the pre-training phase, but I think they do not have a negative impact and thus the choice can be freer. I hope you can feedback here when the test found problems, and I will verify and fix the error.
> 
> 你好，我有点没明白这里，经过了finetuning的三个data_process的步骤后生成的npy文件中的payload，在后续的任务中还会被进一步截断吗？还是npy文件中的就是模型最终的学习内容 Hello,I am also confused about this.Does the data in npy files generated by the data_process/main.py still will be truncated?Or it already is the real thing that model study from?

会的，如果报文过长会被截断。
