### ISSUE TITLE
questions about embedding layer setting on run_classifier.py

### ISSUE THREAD

**Issue by RigCor7** [linwhitehat/ET-BERT#93]
Hello, thanks for your open source.

I'd like to consult whether the embedding layer of the Classifier model in run_classifier.py should repeat to support list formats, like 'word pos seg'. And I wonder if there should be three embedding layers together instead of one.

Thanks a lot.

**Comment by linwhitehat** [comment]
> Hello, thanks for your open source.
> 
> I'd like to consult whether the embedding layer of the Classifier model in run_classifier.py should repeat to support list formats, like 'word pos seg'. And I wonder if there should be three embedding layers together instead of one.
> 
> Thanks a lot.

Hello, RigCor7

Thank you for your interest in our work. In response to your question, we consider as below:

1. Should the embedding layer “repeat” to support multiple inputs like ['word', 'pos', 'seg']?
No, it’s generally not recommended to reuse a single embedding layer for different feature types, as each feature has unique information. Using a single layer risks blending distinct information in ways that may hurt model performance. Instead, separate embeddings should be used for clarity and effectiveness.

2. Should there be three embedding layers for word, pos, and seg?
Yes, it’s better to define three distinct embedding layers for word, pos, and seg. This allows each layer to specialize in learning unique features of each input type. The outputs of these embeddings can then be combined (e.g., via addition or concatenation) before passing them into subsequent layers.

We hope these answers help you.

**Comment by Po-e** [comment]
Thanks for your open source.
I want to learn how the model works to recognize traffic types, but when I run the file 'fine-tuning/run_classifier.py' to fine-tune the pre-train model, it prompts me with 'No such file or directory: 'models/special_tokens_map.json'. I found that there is no such file in this folder, am I missing some key step?

**Comment by RigCor7** [comment]
> > Hello, thanks for your open source.
> > I'd like to consult whether the embedding layer of the Classifier model in run_classifier.py should repeat to support list formats, like 'word pos seg'. And I wonder if there should be three embedding layers together instead of one.
> > Thanks a lot.
> 
> Hello, RigCor7
> 
> Thank you for your interest in our work. In response to your question, we consider as below:
> 
> 1. Should the embedding layer “repeat” to support multiple inputs like ['word', 'pos', 'seg']?
>    No, it’s generally not recommended to reuse a single embedding layer for different feature types, as each feature has unique information. Using a single layer risks blending distinct information in ways that may hurt model performance. Instead, separate embeddings should be used for clarity and effectiveness.
> 2. Should there be three embedding layers for word, pos, and seg?
>    Yes, it’s better to define three distinct embedding layers for word, pos, and seg. This allows each layer to specialize in learning unique features of each input type. The outputs of these embeddings can then be combined (e.g., via addition or concatenation) before passing them into subsequent layers.
> 
> We hope these answers help you.

Thanks for your reply. The "repeat" that I said before is not clear, I mean it's like stack by stack layer, which you have already in the second answer.

**Comment by RigCor7** [comment]
> Thanks for your open source. I want to learn how the model works to recognize traffic types, but when I run the file 'fine-tuning/run_classifier.py' to fine-tune the pre-train model, it prompts me with 'No such file or directory: 'models/special_tokens_map.json'. I found that there is no such file in this folder, am I missing some key step?

it's a file in uer repository, where you can find it.

**Comment by Po-e** [comment]
> > Thanks for your open source. I want to learn how the model works to recognize traffic types, but when I run the file 'fine-tuning/run_classifier.py' to fine-tune the pre-train model, it prompts me with 'No such file or directory: 'models/special_tokens_map.json'. I found that there is no such file in this folder, am I missing some key step?
> 
> it's a file in uer repository, where you can find it.

Thanks for your help.
